# Generated by Django 2.1.2 on 2018-12-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
