# Generated by Django 2.1.2 on 2018-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20181205_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('total_productos', models.IntegerField()),
                ('total_productos_comprados', models.IntegerField()),
                ('total_presupuestado', models.IntegerField()),
                ('total_real', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCliente',
            fields=[
                ('id_producto_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_lista', models.IntegerField()),
                ('id_producto', models.IntegerField()),
            ],
        ),
    ]
