# Generated by Django 2.1.2 on 2018-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20181205_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
