# Generated by Django 2.1.2 on 2018-12-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('nombre_sucursal', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=40)),
            ],
        ),
    ]
